---

# who is the agent (name)
- hosts: db

# we need info about the server
  gather_facts: yes

# we need sudo access
  become: true

- name: install mongo db
  apt: name=mongodb update_cache=yes

# Copy mongod.conf
  - name: Copy default file to web server
    ansible.builtin.copy:
      src: /etc/ansible/eng114_devops/mongod.conf
      dest: /etc/mongodb.conf


# Restart mondogdb
  - name: restart mongodb
    service: name=mongodb state=restarted enabled=yes 