---

# who is the agent (name)
- hosts: web

# we need info about the server
  gather_facts: yes

# we need sudo access
  become: true

# Install NodeJs
  tasks:
  - name: Install Nodejs on web server
    apt: pkg=nodejs state=present

# Install npm
  - name: Install npm on web server
    apt: pkg=npm state=present

# Copy default file
  - name: Copy default file to web server
    ansible.builtin.copy:
      src: /etc/ansible/eng114_devops/default
      dest: /etc/nginx/sites-available/default

# Copy app folder
  - name: Copy app folder to web server
    ansible.builtin.copy:
      src: /etc/ansible/eng114_devops/sre_jenkins_cicd
      dest: home/

# Add db_host env variable
    - name: Insert a line at the end of a file.
      lineinfile:
        path: /etc/bash.bashrc
        line: export DB_HOST='mongodb://192.168.33.11:27017/posts'

  # Restart nginx 
  - name: restart nginx
    service: name=nginx state=restarted enabled=yes