---

- name: tests
  hosts: db
  become: yes
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Timezone
      debug:
        msg: "This machine's timezone is: {{ ansible_date_time.tz }}"

    - name: OS
      debug:
        msg: "This machine's OS is: {{ ansible_os_family }}"



    - name: "Check if Mongodb is installed"
      package_facts:
        manager: "auto"

    - name: confirm Mongodb is installed
      assert:
        that: "'mongodb-org' in ansible_facts.packages"


    - name: Check open ports
      shell: lsof -i -P -n | grep LISTEN
      register: port_check_80

    - name: confirm port 80 is not listening
      assert:
        that: "'*:80 (LISTEN)' not in port_check_80.stdout"


    - name: Check open ports
      shell: lsof -i -P -n | grep LISTEN
      register: port_check_3000

    - name: confirm port 3000 is not listening
      assert:
        that: "'*:3000 (LISTEN)' not in port_check_3000.stdout"

    - name: Check open ports
      shell: lsof -i -P -n | grep LISTEN
      register: port_check_27017

    - name: confirm port 27017 is listening
      assert:
        that: "'*:27017 (LISTEN)' in port_check_27017.stdout"