apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: default 

spec:
  ports:
  - nodePort: 30442
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-app
  type: NodePort